
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode8

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update   ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install http-parser curl mosquitto  ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then wget https://swift.org/builds/development/xcode/swift-DEVELOPMENT-SNAPSHOT-2016-06-20-a/swift-DEVELOPMENT-SNAPSHOT-2016-06-20-a-osx.pkg    ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo installer -pkg swift-DEVELOPMENT-SNAPSHOT-2016-06-20-a-osx.pkg -target /    ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PATH=/Library/Developer/Toolchains/swift-latest.xctoolchain/usr/bin:"${PATH}"    ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then /usr/local/sbin/mosquitto -c /usr/local/etc/mosquitto/mosquitto.conf &   ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget https://swift.org/builds/development/ubuntu1404/swift-DEVELOPMENT-SNAPSHOT-2016-06-20-a/swift-DEVELOPMENT-SNAPSHOT-2016-06-20-a-ubuntu14.04.tar.gz    ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then tar xzvf swift-DEVELOPMENT-SNAPSHOT-2016-06-20-a-ubuntu14.04.tar.gz    ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export PATH=swift-DEVELOPMENT-SNAPSHOT-2016-06-20-a-ubuntu14.04/usr/bin:$PATH    ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -y install clang libicu-dev libkqueue-dev libtool libcurl4-openssl-dev libbsd-dev libblocksruntime-dev build-essential libwrap0-dev libssl-dev libc-ares-dev uuid-dev xsltproc ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then git clone -b experimental/foundation https://github.com/apple/swift-corelibs-libdispatch.git && cd swift-corelibs-libdispatch && git submodule init && git submodule update && sh autogen.sh && ./configure --with-swift-toolchain=${PWD}/../swift-DEVELOPMENT-SNAPSHOT-2016-06-20-a-ubuntu14.04/usr --prefix=${PWD}/../swift-DEVELOPMENT-SNAPSHOT-2016-06-20-a-ubuntu14.04/usr && make && make install && cd ..   ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget http://mosquitto.org/files/source/mosquitto-1.4.8.tar.gz && tar xvzf mosquitto-1.4.8.tar.gz && cd mosquitto-1.4.8  ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make && make install  ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then mosquitto -c /etc/mosquitto/mosquitto.conf  ; fi


script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then swift build -Xcc -fblocks -Xlinker -rpath -Xlinker .build/debug  ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then swift build ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then swift test ; fi
